name: Terraform deployment
on:
  workflow_dispatch:
    inputs:
      image-hash:
        description: 'Image hash to use'
        required: true

env:
  DB_PASS: postgres
  DB_USER: postgres
  DB_NAME: postgres

jobs:

  plan-and-apply:
    name: Plan & Apply Terraform Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform format
        run: terraform fmt -check

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="${{ secrets.TF_STATE_BUCKET }}" \
            -backend-config="key=terraform/state/terraform.tfstate" \
            -backend-config="region=eu-west-1"

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan \
            -no-color \
            -input=false \
            -var="image_hash=${{ github.event.inputs.image-hash }}" \
            -var="db_pass=${{ env.DB_PASS }}" \
            -var="db_user=${{ env.DB_USER }}" \
            -var="db_name=${{ env.DB_NAME }}" \
            -out=create-plan.out \

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false create-plan.out
