name: Terraform deployment
on:
  workflow_dispatch:
    inputs:
      image-hash:
        description: 'Image hash to use'
        required: true

env:
  DB_PASS: postgres
  DB_USER: postgres
  DB_NAME: postgres

jobs:
  plan:
    name: Plan Terraform Deployment
    runs-on: ubuntu-latest
    outputs:
      plan_exitcode: ${{ steps.plan.exitcode }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform format
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan \
            -no-color \
            -input=false \
            -var="image_hash=${{ github.event.inputs.image-hash }}" \
            -var="db_pass=${{ env.DB_PASS }}" \
            -var="db_user=${{ env.DB_USER }}" \
            -var="db_name=${{ env.DB_NAME }}" \
            -out=plan.out \
            -detailed-exitcode
        continue-on-error: true

      - name: Echo Terraform Plan Exit Code
        run: |
          echo "Terraform plan exit code: ${{ steps.plan.outputs.exitcode }}"

      - name: Upload Terraform Plan
        if: steps.plan.exitcode == 2 || steps.plan.exitcode == 0
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: plan.out

      - name: Fail if Plan has Error
        if: steps.plan.exitcode == 1
        run: |
          echo "Terraform plan failed!"
          exit 1

  apply:
    name: Apply Terraform Deployment
    runs-on: ubuntu-latest
    needs: plan
    if: needs.plan.outputs.plan_exitcode == 2

    environment:
      name: dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Download Terraform Plan
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false plan.out
